"""Static limits and glyphs used by listening statistics."""

from app.enums import Daypart

TOP_STATIONS_LIMIT = 10
TREND_DAYS = 14
BAR_GLYPH = "█"
VERTICAL_CHART_MIN_HEIGHT = 3
VERTICAL_CHART_MAX_HEIGHT = 7
VERTICAL_BAR_MAX_WIDTH = 5
STATS_PANEL_BREAKPOINT = 96
STATS_PANEL_GAP = 3
LEGEND_MIN_COLUMN_WIDTH = 26
RANKING_SLOT_MAX_WIDTH = 14
DAYPART_ORDER = (
    Daypart.MORNING,
    Daypart.AFTERNOON,
    Daypart.EVENING,
    Daypart.NIGHT,
)
BAND_ORDER = ("FM", "AM")
OTHER_BAND = "Other"
